@startuml

Gateway -> Gateway : GatewayService::init
activate Gateway #FFBBBB

    Gateway --> Gateway : 1.zTCPTaskPool::init()
    note right Gateway : 客户端线程池
    activate Gateway #DarkSalmon

        Gateway -->> Gateway : 1.1.pVerifyThread->start() \n...
        hnote right #aqua : 连接验证线程(4)
        activate Gateway
        deactivate

        Gateway -->> Gateway : 1.2.syncThread->start()
        hnote right #aqua : 连接同步线程
        activate Gateway
        deactivate

        Gateway -->> Gateway : 1.3.pOkayThread->start() \n...
        hnote right #aqua : 连接处理线程(10)
        activate Gateway
        deactivate

        Gateway -->> Gateway : 1.4.recycleThread->start()
        hnote right #aqua : 连接回收线程
        activate Gateway
        deactivate

    deactivate Gateway

    Gateway --> Gateway : 2.zSubNetService::init()
    activate Gateway #DarkSalmon

        Gateway -> Gateway : superClient->start()
        note right : SuperServer处理线程
        activate Gateway
        deactivate

    deactivate Gateway

    Gateway --> Gateway : 3.sessionClient->start()
    note right : SessionServer处理线程
    activate Gateway #DarkSalmon
    deactivate

    Gateway --> Gateway : 4.accountClient->start()
    note right : BillServer处理线程
    activate Gateway #DarkSalmon
    deactivate

    Gateway --> Gateway : 5.SceneClientManager::init()
    activate Gateway #DarkSalmon

        Gateway -->> Gateway : zTCPClientTaskPool::init()
        activate Gateway

            Gateway -->> Gateway : checkconnectThread->start()
            hnote right #aqua : 检查连接线程
            activate Gateway #Grey
            deactivate

            Gateway -->> Gateway : checkwaitThread->start()
            hnote right #aqua : 等待连接线程
            activate Gateway #Grey
            deactivate

        deactivate

    deactivate


deactivate Gateway

@enduml