@startuml

title Gateway网络层类图

'继承 Extension <|--  继承关系
'组合 Composition *--> 整体由部分构成，整体没有了，部分还存在
'聚合 Aggregation o--> 整体由部分构成，整体没有了，部分不存在

'0.#Moccasin
'1.#LightSeaGreen
'2.#DarkSalmon
'3.#BBBBFF
'4.#SkyBlue
'5.#LightPink
'6.#CadetBlue
'7.#Violet

abstract class zProcessor {
    {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int) = 0;
}

class zNoncopyable {

}

class zThread {
    {method} virtual void run() = 0;
}

'0.服务器类
class zService #Moccasin {
    {method} virtual bool init();
    {method} virtual bool validate();
    {method} virtual void resetLogger();
    {method} virtual void reloadConfig();
    {method} virtual void processException();
    {method} virtual bool final() = 0;
    {method} virtual bool serviceCallback() = 0;

    void main();
}

class zNetService #Moccasin {
    {method} virtual bool init();
    {method} virtual bool final();
    {method] virtual bool validate();
    {method} virtual void newTCPTask(const int, const struct sockaddr_in*);
}

class zSubNetService #Moccasin {
    {method} virtual bool init();
    {method} virtual bool final();
    {method] virtual bool validate();
    {method} virtual void reloadConfig();
    {method} virtual bool msgParse_SuperService(const Cmd::t_NullCmd*, const unsigned int) = 0;
}

class GatewayService #Moccasin {
    {method} virtual bool init();
    {method} virtual bool final();
    {method] virtual bool validate();
    {method} virtual void newTCPTask(const int, const struct sockaddr_in*);
    {method} virtual bool msgParse_SuperService(const Cmd::t_NullCmd*, const unsigned int);
}

'1.主动连接处理类1，自带线程，不能加入线程池
class zTCPClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual void close();
    {method} virtual void sendCmd(const void* pstrCmd, const int nCmdLen);

    {method} bool connect(const char* ip, const unsigned short port);
}

class zTCPBufferClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual void close();
    {method} virtual void sendCmd(const void* pstrCmd, const int nCmdLen);

    {method} bool ListeningRecv();
    {method} bool ListeningSend();
}

class SuperClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

    {method} bool msgParse_Startup(const Cmd::t_NullCmd*, const unsigned int);
}

class SessionClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

    {method} bool connectToSessionServer();
}

class RecordClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

    {method} bool connectToRecordServer();
}

class BillClient #LightSeaGreen {
    {method} virtual void run();
    {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

    {method} bool connectToBillServer();
}

'2.主动连接处理类2，不带线程，需要加入线程池
class zTCPClientTask #DarkSalmon {
    {method} virtual bool connect();
    {method} virtual bool reconnect();
    {method} vritual void addToContainer();
    {method} virtual void removeFromContainer();
    {method} virtual ListeningRecv();
    {method} virtual ListeningSend();
    {method} vritual bool sendCmd(const void* pstrCmd, const int nCmdLen);
}

class SceneClient #DarkSalmon {
   {method} virtual bool connect();
   {method} vritual void addToContainer();
   {method} virtual void removeFromContainer();
   {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

   {method} bool connectToSceneServer();
}

class NpcClient #DarkSalmon {
   {method} virtual bool connect();
   {method} vritual void addToContainer();
   {method} virtual void removeFromContainer();
   {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

   {method} bool connectToNpcServer();
}

class FunctionServerClient #DarkSalmon {
   {method} virtual bool connect();
   {method} vritual void addToContainer();
   {method} virtual void removeFromContainer();
   {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

   {method} bool sendCmd(const void* data, const DWORD size);
}

class BlogServerClient #DarkSalmon {
   {method} virtual bool connect();
   {method} vritual void addToContainer();
   {method} virtual void removeFromContainer();
   {method} virtual bool msgParse(const Cmd::t_NullCmd*, const unsigned int);

   {method} bool sendCmd(const void* data, const DWORD size);
}

'3.被动连接处理类，需要加入线程池
class zTCPTask #BBBBFF {
    SecondMsgQueue msgque2;

    {method} virutal int verifyConn();
    {method} virtual int waitSync();
    {method} virtual int recycleConn();
    {method} virtual void addToContainer();
    {method} virtual void removeFromContainer();
    {method} virtual void Terminate(const TerminateMethod method);
    {method} virutal uniqueAdd();
    {method} virtual uniqueRemove();
    {method} virtual ListeningRecv();
    {method} virtual ListeningSend();
    {method} virtual sendCmd(const void* pstrCmd, int nCmdLen);
    {method} virtual msgParse(const Cmd::t_NullCmd*, const unsigned int);

    {method} virtual isSecondCmd(const Cmd::t_NullCmd*, const unsigned int);
    {method} virtual doSecondCmd(const Cmd::t_NullCmd*, const unsigned int);
}

class GatewayTask #BBBBFF {
    {method} virutal int verifyConn();
    {method} virtual int waitSync();
    {method} virtual int recycleConn();
    {method} virtual void addToContainer();
    {method} virtual void removeFromContainer();
    {method} virutal uniqueAdd();
    {method} virtual uniqueRemove();
    {method} virtual void Terminate(const TerminateMethod method);
    {method} virtual sendCmd(const void* pstrCmd, int nCmdLen);
    {method} virtual msgParse(const Cmd::t_NullCmd* cmd, const unsigned int len);
}

'4.主动连接线程池
class zTCPClientTaskPool #SkyBlue {
    zCheckconnectThread* checkconnectThread;
    zCheckwaitThread* checkwaitThread;
    zThreadGroup taskThreads;

    {method} bool init();
    {method} void addCheckwait(zTCPClientTask*);
    {method} bool addMain(zTCPClientTask*);
}

class zTCPClientTaskQueue #SkyBlue {
    {method} virtual void _add(zTCPClientTask*) = 0;

    {method} void add(zTCPClientTask*);
    {method} void check_queue();
}

class zCheckconnectThread #SkyBlue {
    {method} virtual void run();
}

class zCheckwaitThread #SkyBlue {
    {method} virtual void run();
    {method} virtual void _add(zTCPClientTask*);
}

class zTCPClientTaskThread #SkyBlue {
    {method} virtual void run();
    {method} virtual void _add(zTCPClientTask*);
}

'5.被动连接线程池
class zTCPTaskPool #LightPink {
    zThreadGroup verifyThreads;
    zSyncThread* syncThread;
    zThreadGroup okayThreads;
    zRecycleThread* recycleThread;

    {method} bool init();
    {method} void final();
    {method} void addVerify(zTCPTask*);
    {method} void addSync(zTCPTask*);
    {method} void addOkay(zTCPTask*);
    {method} void addRecycle(zTCPTask*);
}

class zTCPTaskQueue #LightPink {
    {method} virtual void _add(zTCPTask*) = 0;

    {method} void add(zTCPTask*);
    {method} void check_queue();
}

class zVerifyThread #LightPink {
    {method} virtual void run();
    {method} virtual void _add(zTCPTask*);
}

class zSyncThread #LightPink {
    {method} virtual void run();
    {method} virtual void _add(zTCPTask*);
}

class zOkayThread #LightPink {
    {method} virtual void run();
    {method} virtual void _add(zTCPTask*);
}

class zRecycleThread #LightPink {
    {method} virtual void run();
    {method} virtual void _add(zTCPTask*);
}

'0.zService
zNoncopyable <|-- zService
zService <|-- zNetService
zNetService <|-- zSubNetService
zSubNetService <|== GatewayService

'1.zTCPClient
zNoncopyable <|-- zThread
zThread <|-- zTCPClient
zProcessor <|-- zTCPClient

zTCPClient <|-- zTCPBufferClient

zTCPBufferClient <|-- SuperClient
zTCPBufferClient <|-- SessionClient
zTCPBufferClient <|-- BillClient
zTCPBufferClient <|-- RecordClient

'2.zTCPClientTask
zNoncopyable <|-- zTCPClientTask
zProcessor <|-- zTCPClientTask

zTCPClientTask <|-- SceneClient
zTCPClientTask <|-- NpcClient
zTCPClientTask <|-- FunctionServerClient
zTCPClientTask <|-- BlogServerClient

'3.zTCPTask
zNoncopyable <|-- zTCPTask
zProcessor <|-- zTCPTask

zTCPTask <|-- GatewayTask

'4.zTCPClientTaskPool
zNoncopyable <|-- zTCPClientTaskPool

zThread <|-- zCheckconnectThread

zThread <|-- zCheckwaitThread
zTCPClientTaskQueue <|-- zCheckwaitThread

zThread <|-- zTCPClientTaskThread
zTCPClientTaskQueue <|-- zTCPClientTaskThread

zTCPClientTaskPool *--> zCheckconnectThread
zTCPClientTaskPool *--> zCheckwaitThread
zTCPClientTaskPool *--> zTCPClientTaskThread

'5.zTCPTaskPool
zNoncopyable <|-- zTCPTaskPool

zThread <|-- zVerifyThread
zTCPTaskQueue <|-- zVerifyThread

zThread <|-- zSyncThread
zTCPTaskQueue <|-- zSyncThread

zThread <|-- zOkayThread
zTCPTaskQueue <|-- zOkayThread

zThread <|-- zRecycleThread
zTCPTaskQueue <|-- zRecycleThread

zTCPTaskPool *--> zVerifyThread
zTCPTaskPool *--> zSyncThread
zTCPTaskPool *--> zOkayThread
zTCPTaskPool *--> zRecycleThread


@enduml