@startuml

title 消息队列类图

'0.#Moccasin
'1.#LightSeaGreen
'2.#DarkSalmon
'3.#BBBBFF
'4.#SkyBlue
'5.#LightPink
'6.#CadetBlue
'7.#Violet

class MessageQueue {
    // 队列
    - MsgQueue<> cmdQueue;

    // 缓存当前处理的消息
    - char _cmdBuf_[zSocket::MAX_DATASIZE];
    - uint32_t _cmdLen_;

    --
    // 生产
    {method} bool msgParse(const Cmd::t_NullCmd* cmd, const uint32_t cmdLen);

    // 消费所有
    {method} bool doCmd();
    // 消费N条(102400)
    {method} bool doCmdT();
    __

    // 消息处理
    virtual bool cmdMsgParse(const Cmd::t_NullCmd* cmd, const uint32_t cmdLen) = 0;
}

class MsgQueue<QueueSize=102400> {
    // 环形队列
    <是否可写, 消息长度, 消息缓冲区指针>
    - std::pair<volatile bool, std::pair<uint32_t, char*>> cmdQueue[QueueSize];

    // 缓冲队列
    <消息长度， 消息缓冲区指针>
    - std::queue<std::pair<uint32_t, char*>, std::deque<std::pair<uint32_t, char*>>> queueCmd;

    - uint32_t queueWrite;
    - uint32_t queueRead;
    __

    // 压入一条消息
    1.将缓冲队列中的所有消息依次加入环形队列(cmdQueue)，直到环形队列不可写；
    2.缓冲队列为空时，检查环形队列(cmdQueue)是否仍可写；
    3.可写，当前消息加入环形队列；
    4.不可写，当前消息加入缓冲队列；
    bool put(const Cmd::t_NullCmd* cmd, const uint32_t cmdLen);

    // 获取消息（环形队列）
    1.读指针指向标记可读；
    2.返回读指针指向消息；
    std::pair<uint32_t, uint32_t>* get();

    // 删除消息（环形队列）
    1.读指针指向标记置为可写；
    2.读指针+1
    void erase();

    --
    // 将缓冲队列中消息加入环形队列
    bool putQueueToArray(){};
}

MessageQueue *--> MsgQueue

@enduml