@startuml

title 场景九屏类图

'0.#Moccasin
'1.#LightSeaGreen
'2.#DarkSalmon
'3.#BBBBFF
'4.#SkyBlue
'5.#LightPink
'6.#CadetBlue
'7.#Violet

class Scene {

}

class zSceneEntryIndex {
    //<屏索引id, 本屏所有实体对象集合>
    - __gun_cxx::hash_map<uint32_t, std::set<zSceneEntry*>> index[zSceneEntry::SceneEntry_MAX];

    //地图内所有实体对象集合
    - std::set<zSceneEntry*> all[zSceneEntry::SceneEntry_MAX];

    --

    //地图加载时计算-九屏关系
    - __gnu_cxx::hash_map<uint32_t, std::vector<uint32_t>> nine_screen;

    //地图加载时计算-正向八屏关系
    - __gnu_cxx::hash_map<uint32_t, std::vector<uint32_t>> direct_screen[8];

    //地图加载时计算-反向八屏关系
    - __gnu_cxx::hash_map<uint32_t, std::vector<uint32_t>> reverse_direct_screen[8];

    __

}

zSceneEntryIndex <|-- Scene

@enduml