@startuml
'颜色分级1 #DarkKhaki
'颜色分级2 #DarkSalmon
'颜色分级3 #BBBBFF
'颜色分级4 #LightGray
'颜色分级5 默认

title 网关服务器主动角色(图2)

participant Gate
participant Gate_t1
participant Gate_t2
participant Gate_t3
participant Gate_t4

Gate --> Gate : GatewayService::init
activate Gate #DarkKhaki
    Gate --> Gate : ...
    activate Gate #DarkSalmon
    deactivate

    note right Gate #LightBlue: 2.连接到Session(单区只能有一个)
    Gate --> Gate : SessionClient::connectToSessionServer()
    activate Gate #DarkSalmon
        Gate --> Gate : zTCPClient::connect
        activate Gate #BBBBFF
        deactivate
    deactivate
    Gate --> Gate : sessionClient->start()
    activate Gate #DarkSalmon
        Gate -->> Gate_t1
        note over Gate_t1 #goldenrod : Session处理线程

        Gate_t1 --> Gate_t1 : SessionClient::run()
        activate Gate_t1 #DarkKhaki
            Gate_t1 --> Gate_t1 : zTCPBufferClient::run()
            activate Gate_t1 #DarkSalmon
                Gate_t1 --> Gate_t1 : while(...)
                activate Gate_t1 #BBBBFF
                    Gate_t1 --> Gate_t1 : zTCPBufferClient::ListeningRecv(true)
                    activate Gate_t1 #LightGray
                    deactivate

                    Gate_t1 --> Gate_t1 : zTCPBufferClient::ListeningSend()
                    activate Gate_t1 #LightGray
                    deactivate
                deactivate
            deactivate
        deactivate
    deactivate

    Gate --> Gate : ...
    activate Gate #DarkSalmon
    deactivate

    note right Gate #LightBlue: 3.连接到Scene(单区可以有多个)
    Gate --> Gate : SceneClientManager::init()
    activate Gate #DarkSalmon
        Gate --> Gate : zTCPClientTaskPool::init
        activate Gate #BBBBFF

            Gate --> Gate : zCheckconnectThread::start()
            activate Gate #LightGray
                Gate -->> Gate_t2
                note over Gate_t2 #goldenrod : 连接检测线程

                Gate_t2 --> Gate_t2 : zCheckconnectThread::run()
                activate Gate_t2 #DarkKhaki
                    Gate_t2 --> Gate_t2 : zTCPClientTaskPool::timeAction
                    activate Gate_t2 #DarkSalmon
                        Gate_t2 --> Gate_t2 : for(...)
                        activate Gate_t2 #BBBBFF
                            Gate_t2 --> Gate_t2 : zTCPClientTask::connect()
                            activate Gate_t2 #LightGray
                            deactivate

                            Gate_t2 --> Gate_t2 : zTCPClientTaskPool::addCheckwait(zTCPClientTask())
                            activate Gate_t2 #LightGray
                                Gate_t2 --> Gate_t2 : zCheckwaitThread::add(zTCPClientTask())
                                activate Gate_t2
                                deactivate

                                Gate_t2 --> Gate_t2 : zTCPClientTask::getNextState() \n (close -> sync)
                                activate Gate_t2
                                deactivate
                            deactivate
                        deactivate
                    deactivate
                deactivate
            deactivate

            Gate --> Gate : zCheckwaitThread::start()
            activate Gate #LightGray
                Gate -->> Gate_t3
                note over Gate_t3 #goldenrod : 连接等待线程

                Gate_t3 --> Gate_t3 : zCheckwaitThread::run()
                activate Gate_t3 #DarkKhaki
                    Gate_t3 --> Gate_t3 : zTCPClientTaskQueue::check_queue()
                    activate Gate_t3 #DarkSalmon
                    deactivate

                    Gate_t3 --> Gate_t3 : for(...)
                    activate Gate_t3 #DarkSalmon
                        Gate_t3 --> Gate_t3 : zTCPClientTask::checkRebound()
                        activate Gate_t3 #BBBBFF
                        deactivate

                        Gate_t3 --> Gate_t3 : zCheckwaitThread::remove(zTCPClientTask())
                        activate Gate_t3 #BBBBFF
                        deactivate

                        Gate_t3 --> Gate_t3 : zTCPClientTaskPool::addMain()
                        activate Gate_t3 #BBBBFF
                            Gate_t3 --> Gate_t3 : 线程分配
                            activate Gate_t3 #LightGray
                            deactivate

                            Gate_t3 --> Gate_t3 : if (nullptr == taskThread) \n   zTCPClientTaskPool::newThread()
                            activate Gate_t3 #LightGray
                            deactivate

                            Gate_t3 --> Gate_t3 : zTCPClientTaskThread::add(zTCPClientTask())
                            activate Gate_t3 #LightGray
                            deactivate

                            Gate_t3 --> Gate_t3 : zTCPClientTask::getNextState() \n (sync -> okay)
                            activate Gate_t3 #LightGray
                            deactivate
                        deactivate
                    deactivate
                deactivate
            deactivate

            Gate --> Gate : zTCPClientTaskPool::newThread()
            activate Gate #LightGray
                Gate --> Gate : zTCPClientTaskThread::start()
                activate Gate
                    Gate -->> Gate_t4
                    note over Gate_t4 #goldenrod : 主处理线程

                    Gate_t4 --> Gate_t4 : zTCPClientTaskThread::run()
                    activate Gate_t4 #DarkKhaki
                        Gate_t4 --> Gate_t4 : for(...)
                        activate Gate_t4 #DarkSalmon
                            Gate_t4 --> Gate_t4 : zTCPClientTask::ListeningRecv(true)
                            activate Gate_t4 #BBBBFF
                            deactivate

                            Gate_t4 --> Gate_t4 : zTCPClientTask::ListeningSend()
                            activate Gate_t4 #BBBBFF
                            deactivate
                        deactivate
                    deactivate
                deactivate

                Gate --> Gate : zThreadGroup::add(zTCPClientTaskThread())
                activate Gate
                deactivate
            deactivate
        deactivate

        Gate --> Gate : while(...)
        activate Gate #BBBBFF
            Gate --> Gate : zTCPClientTaskPool::put(SceneClient())
            activate Gate #LightGray
            deactivate
        deactivate
    deactivate

    Gate --> Gate : ...
    activate Gate #DarkSalmon
    deactivate

deactivate

@enduml