@startuml
'颜色分级1 #DarkKhaki
'颜色分级2 #DarkSalmon
'颜色分级3 #BBBBFF
'颜色分级4 #LightGray
'颜色分级5 默认

title 网关服务器被动角色(图3)

participant Gate
participant Gate_t1
participant Gate_t2
participant Gate_t3

Gate --> Gate : GatewayService::init
activate Gate #DarkKhaki
    Gate --> Gate : ...
    activate Gate #DarkSalmon
    deactivate

    note right  Gate #LightBlue: 0.网关被动角色
    Gate --> Gate : zTCPTaskPool::init()
    activate Gate #DarkSalmon
        Gate --> Gate : for(...)
        activate Gate #BBBBFF
            Gate --> Gate : pVerifyThread = ZEBRA_NEW zVerifyThread()
            activate Gate #LightGray
            deactivate

            Gate --> Gate : pVerifyThread->start()
            activate Gate #LightGray
                Gate -->> Gate_t1 :
                note over Gate_t1 #goldenrod : 验证线程
            deactivate

            Gate --> Gate : verifyThreads.add(pVerifyThread)
            activate Gate #LightGray
            deactivate
        deactivate

        Gate --> Gate : syncThread = ZEBRA_NEW zSyncThread()
        activate Gate #BBBBFF
        deactivate
        Gate --> Gate : syncThread->start()
        activate Gate #BBBBFF
            Gate -->> Gate_t2 :
            note over Gate_t2 #goldenrod : 同步线程
        deactivate

        Gate --> Gate : for(...)
        activate Gate #BBBBFF
            Gate --> Gate : pOkayThread = ZEBRA_NEW zOkayThread()
            activate Gate #LightGray
            deactivate

            Gate --> Gate : pOkayThread->start()
            activate Gate #LightGray
                Gate -->> Gate_t3 :
                note over Gate_t3 #goldenrod : okay线程
            deactivate

            Gate --> Gate : okayThreads.add(pOkayThread)
            activate Gate #LightGray
            deactivate
        deactivate

        Gate --> Gate : recycleThread = ZEBRA_NEW zRecycleThread()
        activate Gate #BBBBFF
        deactivate
        Gate --> Gate : recycleThread->start()
        activate Gate #BBBBFF
            Gate -->> Gate_t4 :
            note over Gate_t4 #goldenrod : 回收线程
        deactivate
    deactivate

    Gate_t1 --> Gate_t1: zVerifyThread::run()
    activate Gate_t1 #DarkKhaki
        Gate_t1 --> Gate_t1 : zVerifyThread::check_queue()
        activate Gate_t1 #DarkSalmon
        deactivate

        Gate_t1 --> Gate_t1 : for(...)
        activate Gate_t1 #DarkSalmon
            Gate_t1 --> Gate_t1 : GatewayTask::verifyConn()
            activate Gate_t1 #BBBBFF
            deactivate

            Gate_t1 --> Gate_t1 : zVerifyThread::remove(zTCPTask())
            activate Gate_t1 #BBBBFF
            deactivate

            Gate_t1 --> Gate_t1 : GatewayTask::uniqueAdd()
            activate Gate_t1 #BBBBFF
                Gate_t1 --> Gate_t1 : GatewayTaskManager::uniqueAdd()
                activate Gate_t1 #LightGray
                deactivate
            deactivate

            Gate_t1 --> Gate_t1 : zTCPTaskkPool::addSync()
            activate Gate_t1 #BBBBFF
                Gate_t1 --> Gate_t1 : zTCPTask::getNextState()
                activate Gate_t1 #LightGray
                deactivate

                Gate_t1 --> Gate_t1 : zSyncThread::add()
                activate Gate_t1 #LightGray
                    Gate_t1 -->> Gate_t2 : 加入到sync线程任务队列中
                deactivate
            deactivate
        deactivate

        note over Gate_t2 #goldenrod : 同步线程
        Gate_t2 --> Gate_t2 : zSyncThread::run()
        activate Gate_t2 #DarkKhaki
            Gate_t2 --> Gate_t2 : zTCPTaskQueue::check_queue()
            activate Gate_t2 #DarkSalmon
            deactivate

            Gate_t2 --> Gate_t2 : for(...)
            activate Gate_t2 #DarkSalmon
                Gate_t2 --> Gate_t2 : GatewayTask::waitSync()
                activate Gate_t2 #BBBBFF
                deactivate

                Gate_t2 --> Gate_t2 : zSyncThread::addOkay()
                activate Gate_t2 #BBBBFF
                    Gate_t2 -->> Gate_t3 : 加入到okay线程任务队列中
                deactivate
            deactivate
        deactivate

        note over Gate_t3 #goldenrod : okay线程
        Gate_t3 --> Gate_t3 : zOkayThread::run()
        activate Gate_t3 #DarkKhaki
            Gate_t3 --> Gate_t3 : zTCPTaskQueue::check_queue()
            activate Gate_t3 #DarkSalmon
            deactivate

            Gate_t3 --> Gate_t3 : for(...)
            activate Gate_t3 #DarkSalmon
                Gate_t3 --> Gate_t3 : zTCPTask::ListeningRecv(true)
                activate Gate_t3 #BBBBFF
                deactivate

                Gate_t3 --> Gate_t3 : zTCPTask::ListeningSend()
                activate Gate_t3 #BBBBFF
                deactivate
            deactivate
        deactivate

        note over Gate_t4 #goldenrod : 回收线程
        Gate_t4 --> Gate_t4 : zRecycleThread::run()
        activate Gate_t4 #DarkKhaki
            Gate_t4 --> Gate_t4 : zTCPTaskQueue::check_queue()
            activate Gate_t4 #DarkSalmon
            deactivate

            Gate_t4 --> Gate_t4 : for(...)
            activate Gate_t4 #DarkSalmon
                Gate_t4 --> Gate_t4 : GatewayTask::recycleConn()
                activate Gate_t4 #BBBBFF
                deactivate

                Gate_t4 --> Gate_t4 : GatewayTask::uniqueRemove()
                activate Gate_t4 #BBBBFF
                    Gate_t4 --> Gate_t4 : GatewayTaskManager::uniqueRemove()
                    activate Gate_t4 #LightGray
                    deactivate
                deactivate

                Gate_t4 --> Gate_t4 : zTCPTask::getNextState()
                activate Gate_t4 #BBBBFF
                deactivate
            deactivate
        deactivate
    deactivate

    Gate --> Gate : ...
    activate Gate #DarkSalmon
    deactivate

deactivate

@enduml