@startuml

title 服务器启动时序图(以网关为例)

Gateway --> Gateway : GatewayService::init
activate Gateway #FFBBBB
    Gateway --> Gateway : ...
    activate Gateway #DarkSalmon
    deactivate

    Gateway --> Gateway : zSubNetService::init()
    activate Gateway #DarkSalmon
        Gateway -> Super_t1 : 1.Cmd::Super::t_Startup_Request

            Super_t1 --> Super_t1 : zVerifyThread::run()
            activate Super_t1 #FFBBBB
                Super_t1 --> Super_t1 : ServerTask::verifyConn()
                activate Super_t1 #DarkSalmon
                    Super_t1 -> Gateway : 2.Cmd::Super::t_Startup_Response
                deactivate

                Super_t1 --> Super_t1 : zTCPTaskkPool::addSync()
                activate Super_t1 #DarkSalmon
                    Super_t1 --> Super_t1 : zTCPTask::getNextState()
                    activate Super_t1
                    deactivate

                    Super_t1 --> Super_t1 : zSyncThread::add()
                    activate Super_t1
                        Super_t1 -->> Super_t2 : 加入到sync线程任务队列中
                    deactivate
                deactivate
            deactivate

            Super_t2 --> Super_t2 : zSyncThread::run()
            activate Super_t2 #FFBBBB
                Super_t2 --> Super_t2 : ServerTask::waitSync()
                activate Super_t2 #DarkSalmon

                    Super_t2 --> Super_t2 : I.ServerTask::checkSequenceTime()
                    activate Super_t2
                    deactivate

                    Super_t2 --> Super_t2 : II.ServerTask::processSequence()
                    activate Super_t2
                    deactivate

                    Super_t2 --> Super_t2 : III.ServerTask::notifyOther()
                    activate Super_t2
                    deactivate

                    note over Super_t2 : 1.网关依赖服务器均已进入okay状态
                    Super_t2 --> Super_t2 : ServerTask::notifyMe() \n注意:I、II、III均返回true，\n才会通知网关开始初始化
                    activate Super_t2
                        Super_t2 -> Gateway : 3.Cmd::t_Startup_ServerEntry_NotifyMe
                    deactivate
                deactivate
            deactivate
    deactivate

    Gateway --> Gateway : ...
    activate Gateway #DarkSalmon
    deactivate
deactivate

note over Gateway : 2.网关初始化完成

Gateway --> Gateway : zSubNetService::validate()
activate Gateway #FFBBBB
    Gateway -> Super_t2 : 4.Cmd::Super::t_Startup_Ok

    Super_t2 --> Super_t2 : zSyncThread::run()
    activate Super_t2 #FFBBBB
        Super_t2 --> Super_t2 : ServerTask::waitSync()
        activate Super_t2 #DarkSalmon
        deactivate

        Super_t2 --> Super_t2 : zSyncThread::addOkay()
        activate Super_t2 #DarkSalmon
            Super_t2 -->> Super_t3 : 加入到okay线程任务队列中
        deactivate
    deactivate

    Super_t3 --> Super_t3 : ...
    activate Super_t3 #FFBBBB
    deactivate
deactivate

@enduml